services:
  - type: web
    name: smartbi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 180 --workers 2 --keep-alive 5 run:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
