from __future__ import annotations

import csv
import json
from copy import copy
from dataclasses import dataclass
from datetime import UTC, datetime
from io import BytesIO, StringIO
from typing import Any

from app.services.analytics.engine import analyze_dataset
from app.services.comparison_service import ComparisonError, compare_uploads
from app.services.database_service import DatabaseService
from app.services.filter_service import apply_filters


SUPPORTED_FORMATS = {"pdf", "excel", "xlsx", "csv", "json"}


@dataclass(slots=True)
class ReportError(Exception):
    message: str
    status_code: int = 400
    errors: list[str] | None = None


@dataclass(slots=True)
class ReportFile:
    content: bytes
    filename: str
    mimetype: str


def report_metadata() -> dict[str, object]:
    return {
        "message": "Reports endpoint",
        "title": "SmartBI Report",
        "available_formats": ["pdf", "excel", "csv", "json"],
        "download_endpoint": "/api/reports/download",
        "parameters": {
            "required": ["upload_id", "format"],
            "optional": ["compare", "upload_b", "filter parameters"],
        },
    }


def generate_report(
    database_service: DatabaseService,
    upload_id: int,
    report_format: str,
    *,
    filters: dict[str, Any] | None = None,
    compare: bool = False,
    upload_b: int | None = None,
) -> ReportFile:
    normalized_format = _normalize_format(report_format)
    if normalized_format not in SUPPORTED_FORMATS:
        raise ReportError("Unsupported report format.", 400, [report_format])
    if compare and upload_b is None:
        raise ReportError("upload_b is required when compare=true.", 400, ["upload_b"])

    if compare:
        try:
            comparison = compare_uploads(database_service, upload_id, int(upload_b), include_charts=True)
        except ComparisonError as error:
            raise ReportError(error.message, error.status_code, error.errors) from error
        context = _build_comparison_context(comparison)
    else:
        upload, rows = database_service.fetch_upload_dataset(upload_id)
        if upload is None:
            raise ReportError("Upload does not exist.", 404, ["upload_id"])
        if not rows:
            raise ReportError("Upload dataset is empty.", 400, ["upload_id"])
        filtered_rows = apply_filters(rows, filters or {})
        context = _build_dataset_context(upload, filtered_rows, filters or {})

    if normalized_format == "pdf":
        return _build_pdf_report(context)
    if normalized_format == "excel":
        return _build_excel_report(context)
    if normalized_format == "csv":
        return _build_csv_report(context)
    return _build_json_report(context)


def _build_dataset_context(upload: dict[str, Any], rows: list[dict[str, object]], filters: dict[str, Any]) -> dict[str, Any]:
    if not rows:
        raise ReportError("Report dataset is empty after filters were applied.", 400, ["filters"])

    analysis = analyze_dataset(rows)
    return {
        "title": "SmartBI Report",
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "dataset_name": upload.get("file_name", "Dataset"),
        "domain": analysis["domain"],
        "upload": upload,
        "filters": _serialize_filters(filters),
        "kpis": analysis["kpis"],
        "summary_tables": _summary_tables(analysis),
        "charts": analysis["charts"],
        "rows": rows,
        "footer": "Generated by SmartBI",
        "comparison": None,
    }


def _build_comparison_context(comparison: dict[str, Any]) -> dict[str, Any]:
    return {
        "title": "SmartBI Report",
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "dataset_name": f"{comparison['upload_a'].get('file_name')} vs {comparison['upload_b'].get('file_name')}",
        "domain": {"name": comparison["domain"]},
        "upload": comparison["upload_a"],
        "filters": {},
        "kpis": {},
        "summary_tables": {"comparison": comparison["comparison"]},
        "charts": comparison.get("charts", {}),
        "rows": [],
        "footer": "Generated by SmartBI",
        "comparison": comparison,
    }


def _build_pdf_report(context: dict[str, Any]) -> ReportFile:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buffer = BytesIO()
    document = SimpleDocTemplate(buffer, pagesize=A4, title="SmartBI Report")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("SmartBI Report", styles["Title"]),
        Paragraph(f"Generated: {context['generated_at']}", styles["Normal"]),
        Paragraph(f"Dataset: {context['dataset_name']}", styles["Normal"]),
        Paragraph(f"Domain: {context['domain'].get('name', 'Generic')}", styles["Normal"]),
        Spacer(1, 14),
    ]

    _append_pdf_section(story, styles, "Applied Filters", _mapping_rows(context.get("filters", {})))
    _append_pdf_section(story, styles, "KPIs", _mapping_rows(context.get("kpis", {})))
    for section_name, section_payload in context.get("summary_tables", {}).items():
        _append_pdf_section(story, styles, _titleize(section_name), _mapping_rows(section_payload))
    if context.get("comparison"):
        _append_pdf_section(story, styles, "Comparison", _comparison_rows(context["comparison"]["comparison"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph(context["footer"], styles["Italic"]))
    document.build(story, onFirstPage=_draw_pdf_footer, onLaterPages=_draw_pdf_footer)
    return ReportFile(buffer.getvalue(), _filename(context, "pdf"), "application/pdf")


def _append_pdf_section(story: list[Any], styles: Any, title: str, rows: list[list[Any]]) -> None:
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

    story.append(Paragraph(title, styles["Heading2"]))
    if not rows:
        story.append(Paragraph("No data available.", styles["Normal"]))
        story.append(Spacer(1, 10))
        return
    table = Table(rows[:40], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B1424")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#C7D2E1")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.extend([table, Spacer(1, 12)])


def _draw_pdf_footer(canvas: Any, document: Any) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.drawString(40, 24, "SmartBI Report")
    canvas.drawRightString(document.pagesize[0] - 40, 24, f"Page {document.page}")
    canvas.restoreState()


def _build_excel_report(context: dict[str, Any]) -> ReportFile:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    workbook = Workbook()
    summary_sheet = workbook.active
    summary_sheet.title = "Summary"
    _write_rows(summary_sheet, [
        ["SmartBI Report", ""],
        ["Generated", context["generated_at"]],
        ["Dataset", context["dataset_name"]],
        ["Domain", context["domain"].get("name", "Generic")],
    ])
    _style_header(summary_sheet, 1)

    analytics_sheet = workbook.create_sheet("Analytics")
    _write_rows(analytics_sheet, [["Metric", "Value"], *_mapping_rows(context.get("kpis", {}))[1:]])
    _style_header(analytics_sheet, 1)

    if context.get("comparison"):
        comparison_sheet = workbook.create_sheet("Comparison")
        _write_rows(comparison_sheet, _comparison_rows(context["comparison"]["comparison"]))
        _style_header(comparison_sheet, 1)

    raw_sheet = workbook.create_sheet("Raw Data")
    _write_dict_rows(raw_sheet, context.get("rows", []))

    for sheet in workbook.worksheets:
        _auto_width(sheet)
        for cell in sheet[1]:
            cell.font = Font(bold=True)
            cell.fill = PatternFill("solid", fgColor="D9EAF7")

    buffer = BytesIO()
    workbook.save(buffer)
    return ReportFile(buffer.getvalue(), _filename(context, "xlsx"), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")


def _build_csv_report(context: dict[str, Any]) -> ReportFile:
    buffer = StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["SmartBI Report"])
    writer.writerow(["Generated", context["generated_at"]])
    writer.writerow(["Dataset", context["dataset_name"]])
    writer.writerow(["Domain", context["domain"].get("name", "Generic")])
    writer.writerow([])
    writer.writerows(_mapping_rows(context.get("kpis", {})))
    if context.get("comparison"):
        writer.writerow([])
        writer.writerows(_comparison_rows(context["comparison"]["comparison"]))
    if context.get("rows"):
        writer.writerow([])
        rows = context["rows"]
        columns = _columns(rows)
        writer.writerow(columns)
        for row in rows:
            writer.writerow([row.get(column, "") for column in columns])
    return ReportFile(buffer.getvalue().encode("utf-8"), _filename(context, "csv"), "text/csv")


def _build_json_report(context: dict[str, Any]) -> ReportFile:
    return ReportFile(
        json.dumps(context, default=str, indent=2).encode("utf-8"),
        _filename(context, "json"),
        "application/json",
    )


def _summary_tables(analysis: dict[str, Any]) -> dict[str, Any]:
    return {
        "row_summary": {
            "row_count": analysis.get("row_count", 0),
            "column_count": analysis.get("column_count", 0),
        },
        "charts": analysis.get("charts", {}),
    }


def _mapping_rows(payload: Any) -> list[list[Any]]:
    rows = [["Metric", "Value"]]
    flattened = _flatten(payload)
    for key, value in flattened.items():
        rows.append([_titleize(key), value])
    return rows


def _comparison_rows(comparison: dict[str, Any]) -> list[list[Any]]:
    rows = [["Metric", "Old", "New", "Difference", "Growth %", "Trend"]]
    for metric, values in comparison.items():
        rows.append([
            _titleize(metric),
            values.get("old"),
            values.get("new"),
            values.get("difference"),
            values.get("growth_percent"),
            values.get("trend"),
        ])
    return rows


def _flatten(payload: Any, prefix: str = "") -> dict[str, Any]:
    if isinstance(payload, dict):
        if isinstance(payload.get("labels"), list) and isinstance(payload.get("values"), list):
            return {
                f"{prefix}_labels": ", ".join(str(item) for item in payload["labels"][:10]),
                f"{prefix}_values": ", ".join(str(item) for item in payload["values"][:10]),
            }
        flattened: dict[str, Any] = {}
        for key, value in payload.items():
            child_prefix = f"{prefix}_{key}" if prefix else str(key)
            flattened.update(_flatten(value, child_prefix))
        return flattened
    if isinstance(payload, list):
        return {prefix: ", ".join(str(item) for item in payload[:10])}
    return {prefix: payload}


def _write_rows(sheet: Any, rows: list[list[Any]]) -> None:
    for row in rows:
        sheet.append(row)


def _write_dict_rows(sheet: Any, rows: list[dict[str, object]]) -> None:
    columns = _columns(rows)
    if not columns:
        sheet.append(["No raw rows included"])
        return
    sheet.append(columns)
    for row in rows:
        sheet.append([row.get(column, "") for column in columns])


def _style_header(sheet: Any, row_number: int) -> None:
    for cell in sheet[row_number]:
        font = copy(cell.font)
        font.bold = True
        cell.font = font


def _auto_width(sheet: Any) -> None:
    for column_cells in sheet.columns:
        width = max(len(str(cell.value or "")) for cell in column_cells)
        sheet.column_dimensions[column_cells[0].column_letter].width = min(max(width + 2, 12), 48)


def _columns(rows: list[dict[str, object]]) -> list[str]:
    columns: list[str] = []
    for row in rows:
        for column in row:
            if column not in columns:
                columns.append(column)
    return columns


def _serialize_filters(filters: dict[str, Any]) -> dict[str, str]:
    serialized: dict[str, str] = {}
    for key, value in filters.items():
        if isinstance(value, list):
            serialized[key] = ", ".join(str(item) for item in value)
        else:
            serialized[key] = str(value)
    return serialized


def _normalize_format(report_format: str) -> str:
    normalized = str(report_format).strip().lower()
    return "excel" if normalized == "xlsx" else normalized


def _filename(context: dict[str, Any], extension: str) -> str:
    dataset = str(context.get("dataset_name", "smartbi")).replace(" ", "_").replace(".", "_")
    return f"smartbi_report_{dataset}.{extension}"


def _titleize(value: str) -> str:
    return str(value).replace("_", " ").title()
